global using APIIntegartion;
global using Integration;
global using System.Text.Json;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Text;
global using Microsoft.AspNetCore.JsonPatch;
global using Newtonsoft.Json;
global using System.Diagnostics;